### ISSUE TITLE
Add support for ArrowUp and ArrowDown (as sent by a remote control)

### ISSUE THREAD

**Issue by HeikoSchlittermann** [ionelmc/python-darkslide#12]

**Comment by HeikoSchlittermann** [comment]
I use a simple remote control (Laser Pointer). This control sends TAB, ArrowUp and ArrowDown Keyboard events. I'd like to see darkslide (the browser) respond to these events.

If possible, I'll create a pull request

**Comment by ionelmc** [comment]
Thanks, there will be a new release soon.

**Comment by ionelmc** [comment]
Released 5.0.0.

**Comment by HeikoSchlittermann** [comment]
Ionel Cristian Mărieș <notifications@github.com> (So 29 Sep 2019 16:17:41 CEST):
> Closed #12.

Cool. Thank you.
--
Heiko
