### ISSUE TITLE
open source PDF export

### ISSUE THREAD

**Issue by Matthias84** [ionelmc/python-darkslide#2]
Hi there, the current PDF engine is sadly an commercial product. Are there any plans to replace it with an open source component? What are the technical requirements?

**Comment by ionelmc** [comment]
Huh. I didn't even notice it's commercial (I just forked this project from landslide).

I think something can be worked out, perhaps using Chrome's pdf print mode? How about that?

**Comment by ionelmc** [comment]
I'd look like this 
[darkslide-examples.pdf](https://github.com/ionelmc/python-darkslide/files/1395962/darkslide-examples.pdf)

**Comment by Matthias84** [comment]
The result is pretty nice, but personally I would preffer an non-browser approach to minimize dependencies and allow easy automatisation?

**Comment by ionelmc** [comment]
Well ... I'd very much like to solve this but then again, I just use chrome's pdf export when I need a pdf. Maybe I should just remove the pdf output support, it seems useless for most ppl.

**Comment by ionelmc** [comment]
Anyway... seems there's http://weasyprint.org/ or https://wkhtmltopdf.org/

Worth trying.

**Comment by ionelmc** [comment]
Well... weasyprint don't support many things like flex layouts, text shadows, javascript and probably many other important things. So it's a no.

And wkhtmltopdf is horrendously broken, doesn't even render anything.

I think I'm just gonna remove the feature. If anyone is using prince, and if it even works at all, they can just run it manually.
