### ISSUE TITLE
Useless prefix `450|` in QR Code example?

### ISSUE THREAD

**Issue by pmhahn** [ionelmc/python-darkslide#23]
In the [README.rst](README.rst) the example for  [QR-Codes](https://pypi.org/project/darkslide/#qr-codes) has this:

> .qr: 450|https://github.com/ionelmc/python-darkslide

The prefix `450|` was added with 2577a367 for #2 by @ionelmc , but I cannot figure out for what: It is embedded within the URL, which makes it invalid.
Please remove it or at least add a comment explaining the prefix.

**Comment by ionelmc** [comment]
Ooof. It was a width. I need to check if it still works, yes...

**Comment by ionelmc** [comment]
It doesn't, I'll remove that part from the readme.
